basePath: /
host: localhost:8000
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a Go Expert API Example.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
